query Profile {
  profile {
    id
    firstName
    lastName
    email
    role
    groups {
      id
      name
      members {
        id
        firstName
        lastName
        email
      }
    }
  }
}
