query Channel($channelId: Float!, $groupId: Float!) {
  channel(channelId: $channelId, groupId: $groupId) {
    id
    group {
      members {
        id
        firstName
        lastName
      }
    }
    receiver {
      id
    }
  }
}
