query Messages($channelId: Int, $groupId: Float) {
  messages(channelId: $channelId, groupId: $groupId) {
    id
    content
    sent_at
    writtenBy {
      id
      firstName
      lastName
    }
    channelId {
      id
    }
    likes {
      id
    }
    groupId {
      id
    }
  }
}
