query Messages($channelId: Int) {
  messages(channelId: $channelId) {
    id
    content
    sent_at
    writtenBy {
      id
      firstName
      lastName
    }
    channelId {
      id
    }
  }
}
